server:
  port: 80  #启动端口

spring:
  #连接数据库的配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///sp
    username: root
    password: root

  #thymeleaf配置
  thymeleaf:
    cache: false  #缓存设置为false, 这样修改之后马上生效，便于调试

mybatis:
  #Mapper.xml的配置文件位置
  mapper-locations: classpath:com/sp/dao/*.xml
  #别名
  type-aliases-package: com.sp.entity












